package uk.co.noetic.kaba;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-10-26T10:26:57.365+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://tempuri.org", name = "MessengerPMSWSServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MessengerPMSWSServiceSoap {

    /**
     * Existing keys access (new or duplicate) will not be modified, and will not carry any of the updated information.   This key will not override older keys, i.e. cancel old keys.
     */
    @WebResult(name = "ChangeGuestAccessResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "ChangeGuestAccess", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.ChangeGuestAccess")
    @WebMethod(operationName = "ChangeGuestAccess", action = "http://tempuri.org/ChangeGuestAccess")
    @ResponseWrapper(localName = "ChangeGuestAccessResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.ChangeGuestAccessResponse")
    public uk.co.noetic.kaba.ChangeGuestAccessResponse.ChangeGuestAccessResult changeGuestAccess(
        @WebParam(name = "ReservationID", targetNamespace = "http://tempuri.org")
        java.lang.String reservationID,
        @WebParam(name = "SiteName", targetNamespace = "http://tempuri.org")
        java.lang.String siteName,
        @WebParam(name = "PMSTerminalID", targetNamespace = "http://tempuri.org")
        java.lang.String pmsTerminalID,
        @WebParam(name = "MainRoomNo", targetNamespace = "http://tempuri.org")
        java.lang.String mainRoomNo,
        @WebParam(name = "RoomList", targetNamespace = "http://tempuri.org")
        uk.co.noetic.kaba.ArrayOfString roomList
    );

    /**
     * Access will be blocked immediately to all rooms for all keys created with this Reservation ID.
     */
    @WebResult(name = "DenyAccessToGuestResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "DenyAccessToGuest", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.DenyAccessToGuest")
    @WebMethod(operationName = "DenyAccessToGuest", action = "http://tempuri.org/DenyAccessToGuest")
    @ResponseWrapper(localName = "DenyAccessToGuestResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.DenyAccessToGuestResponse")
    public uk.co.noetic.kaba.DenyAccessToGuestResponse.DenyAccessToGuestResult denyAccessToGuest(
        @WebParam(name = "ReservationID", targetNamespace = "http://tempuri.org")
        java.lang.String reservationID,
        @WebParam(name = "SiteName", targetNamespace = "http://tempuri.org")
        java.lang.String siteName,
        @WebParam(name = "PMSTerminalID", targetNamespace = "http://tempuri.org")
        java.lang.String pmsTerminalID
    );

    /**
     * This will create a  new key which, will remove access to all previously encoded keys that have access to the rooms. For variable room list selection, must have smartcards or memory card technology.
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "CreateNewBookingResponse", targetNamespace = "http://tempuri.org", partName = "parameters")
    @WebMethod(operationName = "CreateNewBooking", action = "http://tempuri.org/CreateNewBooking")
    public CreateNewBookingResponse createNewBooking(
        @WebParam(partName = "parameters", name = "CreateNewBooking", targetNamespace = "http://tempuri.org")
        CreateNewBooking parameters
    );

    /**
     * Hello OOOOOO simple.
     */
    @WebResult(name = "HelloWorldTestResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "HelloWorldTest", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.HelloWorldTest")
    @WebMethod(operationName = "HelloWorldTest", action = "http://tempuri.org/HelloWorldTest")
    @ResponseWrapper(localName = "HelloWorldTestResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.HelloWorldTestResponse")
    public java.lang.String helloWorldTest(
        @WebParam(name = "s1", targetNamespace = "http://tempuri.org")
        java.lang.String s1,
        @WebParam(name = "i1", targetNamespace = "http://tempuri.org")
        int i1
    );

    /**
     * Will be added to the room(s) which were already booked, by Original Booker,  without removing access to other users. Additional rooms will be shared only if the rooms have been booked by the same  Original Booker or are free.
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "AddSharedGuestResponse", targetNamespace = "http://tempuri.org", partName = "parameters")
    @WebMethod(operationName = "AddSharedGuest", action = "http://tempuri.org/AddSharedGuest")
    public AddSharedGuestResponse addSharedGuest(
        @WebParam(partName = "parameters", name = "AddSharedGuest", targetNamespace = "http://tempuri.org")
        AddSharedGuest parameters
    );

    /**
     * The Reservation must have a key which has not expired. Must have been previously created.
     */
    @WebResult(name = "MakeDuplicateKeyResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "MakeDuplicateKey", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.MakeDuplicateKey")
    @WebMethod(operationName = "MakeDuplicateKey", action = "http://tempuri.org/MakeDuplicateKey")
    @ResponseWrapper(localName = "MakeDuplicateKeyResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.MakeDuplicateKeyResponse")
    public uk.co.noetic.kaba.MakeDuplicateKeyResponse.MakeDuplicateKeyResult makeDuplicateKey(
        @WebParam(name = "ReservationID", targetNamespace = "http://tempuri.org")
        java.lang.String reservationID,
        @WebParam(name = "SiteName", targetNamespace = "http://tempuri.org")
        java.lang.String siteName,
        @WebParam(name = "PMSTerminalID", targetNamespace = "http://tempuri.org")
        java.lang.String pmsTerminalID,
        @WebParam(name = "EncoderID", targetNamespace = "http://tempuri.org")
        java.lang.String encoderID,
        @WebParam(name = "KeyCount", targetNamespace = "http://tempuri.org")
        long keyCount,
        @WebParam(name = "KeySize", targetNamespace = "http://tempuri.org")
        long keySize,
        @WebParam(name = "UID", targetNamespace = "http://tempuri.org")
        java.lang.String uid,
        @WebParam(name = "GuestName", targetNamespace = "http://tempuri.org")
        java.lang.String guestName
    );

    /**
     * This method has been included to publish complex types associated with each method return. The header Action attribut will be set to http://www.w3.org/2005/08/addressing/fault to trigger fault processing.
     */
    @WebResult(name = "PublishFaultListResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "PublishFaultList", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.PublishFaultList")
    @WebMethod(operationName = "PublishFaultList", action = "http://tempuri.org/PublishFaultList")
    @ResponseWrapper(localName = "PublishFaultListResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.PublishFaultListResponse")
    public uk.co.noetic.kaba.PublishFaultListResponse.PublishFaultListResult publishFaultList();

    /**
     * This will update the PMS transaction status.
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "UpdateKeyTransactionStatusResponse", targetNamespace = "http://tempuri.org", partName = "parameters")
    @WebMethod(operationName = "UpdateKeyTransactionStatus", action = "http://tempuri.org/UpdateKeyTransactionStatus")
    public UpdateKeyTransactionStatusResponse updateKeyTransactionStatus(
        @WebParam(partName = "parameters", name = "UpdateKeyTransactionStatus", targetNamespace = "http://tempuri.org")
        UpdateKeyTransactionStatus parameters
    );

    /**
     * All guests and reservations of a room will be canceled and denied access to room(s) provided.
     */
    @WebResult(name = "CancelGuestsAccessToRoomResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "CancelGuestsAccessToRoom", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.CancelGuestsAccessToRoom")
    @WebMethod(operationName = "CancelGuestsAccessToRoom", action = "http://tempuri.org/CancelGuestsAccessToRoom")
    @ResponseWrapper(localName = "CancelGuestsAccessToRoomResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.CancelGuestsAccessToRoomResponse")
    public uk.co.noetic.kaba.CancelGuestsAccessToRoomResponse.CancelGuestsAccessToRoomResult cancelGuestsAccessToRoom(
        @WebParam(name = "SiteName", targetNamespace = "http://tempuri.org")
        java.lang.String siteName,
        @WebParam(name = "MainRoomNo", targetNamespace = "http://tempuri.org")
        java.lang.String mainRoomNo,
        @WebParam(name = "PMSTerminalID", targetNamespace = "http://tempuri.org")
        java.lang.String pmsTerminalID
    );

    /**
     * Will be done remotely to all rooms associated with this Resv ID.
     */
    @WebResult(name = "ExtendCheckOutResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "ExtendCheckOut", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.ExtendCheckOut")
    @WebMethod(operationName = "ExtendCheckOut", action = "http://tempuri.org/ExtendCheckOut")
    @ResponseWrapper(localName = "ExtendCheckOutResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.ExtendCheckOutResponse")
    public uk.co.noetic.kaba.ExtendCheckOutResponse.ExtendCheckOutResult extendCheckOut(
        @WebParam(name = "ReservationID", targetNamespace = "http://tempuri.org")
        java.lang.String reservationID,
        @WebParam(name = "SiteName", targetNamespace = "http://tempuri.org")
        java.lang.String siteName,
        @WebParam(name = "PMSTerminalID", targetNamespace = "http://tempuri.org")
        java.lang.String pmsTerminalID,
        @WebParam(name = "CheckOut", targetNamespace = "http://tempuri.org")
        javax.xml.datatype.XMLGregorianCalendar checkOut
    );

    /**
     * Use this Web Method to generate Sector Key A.
     */
    @RequestWrapper(localName = "GetDeviceSecKeysRights", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.GetDeviceSecKeysRights")
    @WebMethod(operationName = "GetDeviceSecKeysRights", action = "http://tempuri.org/GetDeviceSecKeysRights")
    @ResponseWrapper(localName = "GetDeviceSecKeysRightsResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.GetDeviceSecKeysRightsResponse")
    public void getDeviceSecKeysRights(
        @WebParam(mode = WebParam.Mode.INOUT, name = "keyReq", targetNamespace = "http://tempuri.org")
        javax.xml.ws.Holder<CSecKeysRequest> keyReq,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetDeviceSecKeysRightsResult", targetNamespace = "http://tempuri.org")
        javax.xml.ws.Holder<uk.co.noetic.kaba.GetDeviceSecKeysRightsResponse.GetDeviceSecKeysRightsResult> getDeviceSecKeysRightsResult
    );

    /**
     * This will remove the Staff PMS transaction.
     */
    @WebResult(name = "UnRegisterStaffResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "UnRegisterStaff", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.UnRegisterStaff")
    @WebMethod(operationName = "UnRegisterStaff", action = "http://tempuri.org/UnRegisterStaff")
    @ResponseWrapper(localName = "UnRegisterStaffResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.UnRegisterStaffResponse")
    public uk.co.noetic.kaba.CMessengerGuestCreateResponse unRegisterStaff(
        @WebParam(name = "StaffID", targetNamespace = "http://tempuri.org")
        java.lang.String staffID,
        @WebParam(name = "MobileNumber", targetNamespace = "http://tempuri.org")
        java.lang.String mobileNumber,
        @WebParam(name = "KeyName", targetNamespace = "http://tempuri.org")
        java.lang.String keyName,
        @WebParam(name = "KeyData", targetNamespace = "http://tempuri.org")
        byte[] keyData
    );

    /**
     * This will create a new key with limited use and will not remove access to all previously encoded keys that have access to the rooms.
     */
    @WebResult(name = "CreateOneShotKeyResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "CreateOneShotKey", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.CreateOneShotKey")
    @WebMethod(operationName = "CreateOneShotKey", action = "http://tempuri.org/CreateOneShotKey")
    @ResponseWrapper(localName = "CreateOneShotKeyResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.CreateOneShotKeyResponse")
    public uk.co.noetic.kaba.CreateOneShotKeyResponse.CreateOneShotKeyResult createOneShotKey(
        @WebParam(name = "SiteName", targetNamespace = "http://tempuri.org")
        java.lang.String siteName,
        @WebParam(name = "PMSTerminalID", targetNamespace = "http://tempuri.org")
        java.lang.String pmsTerminalID,
        @WebParam(name = "EncoderID", targetNamespace = "http://tempuri.org")
        java.lang.String encoderID,
        @WebParam(name = "MainRoomNo", targetNamespace = "http://tempuri.org")
        java.lang.String mainRoomNo,
        @WebParam(name = "CheckIn", targetNamespace = "http://tempuri.org")
        javax.xml.datatype.XMLGregorianCalendar checkIn,
        @WebParam(name = "CheckOut", targetNamespace = "http://tempuri.org")
        javax.xml.datatype.XMLGregorianCalendar checkOut,
        @WebParam(name = "KeySize", targetNamespace = "http://tempuri.org")
        long keySize,
        @WebParam(name = "UID", targetNamespace = "http://tempuri.org")
        java.lang.String uid
    );

    /**
     * Access will be unblocked immediately to all rooms for all keys created with this Reservation ID UNLESS the rooms have been re-booked.
     */
    @WebResult(name = "ReEstablishAccessToGuestResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "ReEstablishAccessToGuest", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.ReEstablishAccessToGuest")
    @WebMethod(operationName = "ReEstablishAccessToGuest", action = "http://tempuri.org/ReEstablishAccessToGuest")
    @ResponseWrapper(localName = "ReEstablishAccessToGuestResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.ReEstablishAccessToGuestResponse")
    public uk.co.noetic.kaba.ReEstablishAccessToGuestResponse.ReEstablishAccessToGuestResult reEstablishAccessToGuest(
        @WebParam(name = "ReservationID", targetNamespace = "http://tempuri.org")
        java.lang.String reservationID,
        @WebParam(name = "SiteName", targetNamespace = "http://tempuri.org")
        java.lang.String siteName,
        @WebParam(name = "PMSTerminalID", targetNamespace = "http://tempuri.org")
        java.lang.String pmsTerminalID
    );

    /**
     * This method has been included to publish complex types associated with each method return. The header Action attribut will be set to http://www.w3.org/2005/08/addressing/fault to trigger fault processing.
     */
    @WebResult(name = "PublishResponseComplexTypesResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "PublishResponseComplexTypes", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.PublishResponseComplexTypes")
    @WebMethod(operationName = "PublishResponseComplexTypes", action = "http://tempuri.org/PublishResponseComplexTypes")
    @ResponseWrapper(localName = "PublishResponseComplexTypesResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.PublishResponseComplexTypesResponse")
    public uk.co.noetic.kaba.PublishResponseComplexTypesResponse.PublishResponseComplexTypesResult publishResponseComplexTypes(
        @WebParam(name = "DummyResponse", targetNamespace = "http://tempuri.org")
        uk.co.noetic.kaba.CMessengerResponse dummyResponse,
        @WebParam(name = "DummyFault", targetNamespace = "http://tempuri.org")
        uk.co.noetic.kaba.Fault dummyFault,
        @WebParam(name = "aReason", targetNamespace = "http://tempuri.org")
        uk.co.noetic.kaba.EMainFaultReasons aReason,
        @WebParam(name = "aDetailReason", targetNamespace = "http://tempuri.org")
        uk.co.noetic.kaba.EDetailEncoderFaultReasons aDetailReason
    );

    /**
     * You can not have 2 different unassigned guests merged into the same room unless one of the keys is re-encoded.
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "MakeUnassignedBookingResponse", targetNamespace = "http://tempuri.org", partName = "parameters")
    @WebMethod(operationName = "MakeUnassignedBooking", action = "http://tempuri.org/MakeUnassignedBooking")
    public MakeUnassignedBookingResponse makeUnassignedBooking(
        @WebParam(partName = "parameters", name = "MakeUnassignedBooking", targetNamespace = "http://tempuri.org")
        MakeUnassignedBooking parameters
    );

    /**
     * Will send a DenyAccessToUser with the Reservation # after the grace period has ended.
     */
    @WebResult(name = "CheckOutGuestResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "CheckOutGuest", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.CheckOutGuest")
    @WebMethod(operationName = "CheckOutGuest", action = "http://tempuri.org/CheckOutGuest")
    @ResponseWrapper(localName = "CheckOutGuestResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.CheckOutGuestResponse")
    public uk.co.noetic.kaba.CheckOutGuestResponse.CheckOutGuestResult checkOutGuest(
        @WebParam(name = "ReservationID", targetNamespace = "http://tempuri.org")
        java.lang.String reservationID,
        @WebParam(name = "SiteName", targetNamespace = "http://tempuri.org")
        java.lang.String siteName,
        @WebParam(name = "PMSTerminalID", targetNamespace = "http://tempuri.org")
        java.lang.String pmsTerminalID
    );

    /**
     * Existing keys access (new or duplicate) will not be modified, and will not carry any of the updated information.   This key will not override older keys, i.e. cancel old keys.
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ChangeKeyAccessResponse", targetNamespace = "http://tempuri.org", partName = "parameters")
    @WebMethod(operationName = "ChangeKeyAccess", action = "http://tempuri.org/ChangeKeyAccess")
    public ChangeKeyAccessResponse changeKeyAccess(
        @WebParam(partName = "parameters", name = "ChangeKeyAccess", targetNamespace = "http://tempuri.org")
        ChangeKeyAccess parameters
    );

    /**
     * All guests and reservations of a room will be canceled and denied access to room(s) provided.
     */
    @WebResult(name = "CancelGuestsMobileAccessToRoomResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "CancelGuestsMobileAccessToRoom", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.CancelGuestsMobileAccessToRoom")
    @WebMethod(operationName = "CancelGuestsMobileAccessToRoom", action = "http://tempuri.org/CancelGuestsMobileAccessToRoom")
    @ResponseWrapper(localName = "CancelGuestsMobileAccessToRoomResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.CancelGuestsMobileAccessToRoomResponse")
    public uk.co.noetic.kaba.CancelGuestsMobileAccessToRoomResponse.CancelGuestsMobileAccessToRoomResult cancelGuestsMobileAccessToRoom(
        @WebParam(name = "SiteName", targetNamespace = "http://tempuri.org")
        java.lang.String siteName,
        @WebParam(name = "ReservationID", targetNamespace = "http://tempuri.org")
        java.lang.String reservationID,
        @WebParam(name = "MainRoomNo", targetNamespace = "http://tempuri.org")
        java.lang.String mainRoomNo,
        @WebParam(name = "GuestMobileNumber", targetNamespace = "http://tempuri.org")
        java.lang.String guestMobileNumber,
        @WebParam(name = "PMSTerminalID", targetNamespace = "http://tempuri.org")
        java.lang.String pmsTerminalID
    );

    /**
     * This will create the Staff PMS transaction.
     */
    @WebResult(name = "SendKey2StaffMobileDeviceResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "SendKey2StaffMobileDevice", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.SendKey2StaffMobileDevice")
    @WebMethod(operationName = "SendKey2StaffMobileDevice", action = "http://tempuri.org/SendKey2StaffMobileDevice")
    @ResponseWrapper(localName = "SendKey2StaffMobileDeviceResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.SendKey2StaffMobileDeviceResponse")
    public uk.co.noetic.kaba.CMessengerGuestCreateResponse sendKey2StaffMobileDevice(
        @WebParam(name = "PMSTerminalID", targetNamespace = "http://tempuri.org")
        java.lang.String pmsTerminalID,
        @WebParam(name = "ValidFrom", targetNamespace = "http://tempuri.org")
        javax.xml.datatype.XMLGregorianCalendar validFrom,
        @WebParam(name = "ValidTo", targetNamespace = "http://tempuri.org")
        javax.xml.datatype.XMLGregorianCalendar validTo,
        @WebParam(name = "StaffID", targetNamespace = "http://tempuri.org")
        java.lang.String staffID,
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org")
        java.lang.String name,
        @WebParam(name = "MobileNumber", targetNamespace = "http://tempuri.org")
        java.lang.String mobileNumber,
        @WebParam(name = "KeyName", targetNamespace = "http://tempuri.org")
        java.lang.String keyName,
        @WebParam(name = "KeyData", targetNamespace = "http://tempuri.org")
        byte[] keyData,
        @WebParam(name = "SendSMS", targetNamespace = "http://tempuri.org")
        boolean sendSMS
    );

    /**
     * This will get all PMS transactions history according to some filters.
     */
    @WebResult(name = "GetMobileTransactionHistoryResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "GetMobileTransactionHistory", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.GetMobileTransactionHistory")
    @WebMethod(operationName = "GetMobileTransactionHistory", action = "http://tempuri.org/GetMobileTransactionHistory")
    @ResponseWrapper(localName = "GetMobileTransactionHistoryResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.GetMobileTransactionHistoryResponse")
    public uk.co.noetic.kaba.MobileTransactionHistory getMobileTransactionHistory(
        @WebParam(name = "ReservationID", targetNamespace = "http://tempuri.org")
        java.lang.String reservationID,
        @WebParam(name = "RoomNo", targetNamespace = "http://tempuri.org")
        java.lang.String roomNo,
        @WebParam(name = "EncoderID", targetNamespace = "http://tempuri.org")
        java.lang.String encoderID,
        @WebParam(name = "From", targetNamespace = "http://tempuri.org")
        javax.xml.datatype.XMLGregorianCalendar from,
        @WebParam(name = "To", targetNamespace = "http://tempuri.org")
        javax.xml.datatype.XMLGregorianCalendar to
    );

    /**
     * Will add access to the targetted rooms. In a shared with context the new rooms must be either empty or belong to the same booking, i.e.  Shared with users all share a same special key.
     */
    @WebResult(name = "AddGuestAccessResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "AddGuestAccess", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.AddGuestAccess")
    @WebMethod(operationName = "AddGuestAccess", action = "http://tempuri.org/AddGuestAccess")
    @ResponseWrapper(localName = "AddGuestAccessResponse", targetNamespace = "http://tempuri.org", className = "uk.co.noetic.kaba.AddGuestAccessResponse")
    public uk.co.noetic.kaba.AddGuestAccessResponse.AddGuestAccessResult addGuestAccess(
        @WebParam(name = "ReservationID", targetNamespace = "http://tempuri.org")
        java.lang.String reservationID,
        @WebParam(name = "SiteName", targetNamespace = "http://tempuri.org")
        java.lang.String siteName,
        @WebParam(name = "PMSTerminalID", targetNamespace = "http://tempuri.org")
        java.lang.String pmsTerminalID,
        @WebParam(name = "RoomList", targetNamespace = "http://tempuri.org")
        uk.co.noetic.kaba.ArrayOfString roomList
    );
}
