
package uk.co.noetic.kaba;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-10-26T10:26:57.286+05:30
 * Generated source version: 2.7.18
 * 
 */
public final class MessengerPMSWSServiceSoap_MessengerPMSWSServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org", "MessengerPMSWSService");

    private MessengerPMSWSServiceSoap_MessengerPMSWSServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MessengerPMSWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MessengerPMSWSService ss = new MessengerPMSWSService(wsdlURL, SERVICE_NAME);
        MessengerPMSWSServiceSoap port = ss.getMessengerPMSWSServiceSoap();  
        
        {
        System.out.println("Invoking changeGuestAccess...");
        java.lang.String _changeGuestAccess_reservationID = "";
        java.lang.String _changeGuestAccess_siteName = "";
        java.lang.String _changeGuestAccess_pmsTerminalID = "";
        java.lang.String _changeGuestAccess_mainRoomNo = "";
        uk.co.noetic.kaba.ArrayOfString _changeGuestAccess_roomList = null;
        uk.co.noetic.kaba.ChangeGuestAccessResponse.ChangeGuestAccessResult _changeGuestAccess__return = port.changeGuestAccess(_changeGuestAccess_reservationID, _changeGuestAccess_siteName, _changeGuestAccess_pmsTerminalID, _changeGuestAccess_mainRoomNo, _changeGuestAccess_roomList);
        System.out.println("changeGuestAccess.result=" + _changeGuestAccess__return);


        }
        {
        System.out.println("Invoking denyAccessToGuest...");
        java.lang.String _denyAccessToGuest_reservationID = "";
        java.lang.String _denyAccessToGuest_siteName = "";
        java.lang.String _denyAccessToGuest_pmsTerminalID = "";
        uk.co.noetic.kaba.DenyAccessToGuestResponse.DenyAccessToGuestResult _denyAccessToGuest__return = port.denyAccessToGuest(_denyAccessToGuest_reservationID, _denyAccessToGuest_siteName, _denyAccessToGuest_pmsTerminalID);
        System.out.println("denyAccessToGuest.result=" + _denyAccessToGuest__return);


        }
        {
        System.out.println("Invoking createNewBooking...");
        uk.co.noetic.kaba.CreateNewBooking _createNewBooking_parameters = null;
        uk.co.noetic.kaba.CreateNewBookingResponse _createNewBooking__return = port.createNewBooking(_createNewBooking_parameters);
        System.out.println("createNewBooking.result=" + _createNewBooking__return);


        }
        {
        System.out.println("Invoking helloWorldTest...");
        java.lang.String _helloWorldTest_s1 = "";
        int _helloWorldTest_i1 = 0;
        java.lang.String _helloWorldTest__return = port.helloWorldTest(_helloWorldTest_s1, _helloWorldTest_i1);
        System.out.println("helloWorldTest.result=" + _helloWorldTest__return);


        }
        {
        System.out.println("Invoking addSharedGuest...");
        uk.co.noetic.kaba.AddSharedGuest _addSharedGuest_parameters = null;
        uk.co.noetic.kaba.AddSharedGuestResponse _addSharedGuest__return = port.addSharedGuest(_addSharedGuest_parameters);
        System.out.println("addSharedGuest.result=" + _addSharedGuest__return);


        }
        {
        System.out.println("Invoking makeDuplicateKey...");
        java.lang.String _makeDuplicateKey_reservationID = "";
        java.lang.String _makeDuplicateKey_siteName = "";
        java.lang.String _makeDuplicateKey_pmsTerminalID = "";
        java.lang.String _makeDuplicateKey_encoderID = "";
        long _makeDuplicateKey_keyCount = 0;
        long _makeDuplicateKey_keySize = 0;
        java.lang.String _makeDuplicateKey_uid = "";
        java.lang.String _makeDuplicateKey_guestName = "";
        uk.co.noetic.kaba.MakeDuplicateKeyResponse.MakeDuplicateKeyResult _makeDuplicateKey__return = port.makeDuplicateKey(_makeDuplicateKey_reservationID, _makeDuplicateKey_siteName, _makeDuplicateKey_pmsTerminalID, _makeDuplicateKey_encoderID, _makeDuplicateKey_keyCount, _makeDuplicateKey_keySize, _makeDuplicateKey_uid, _makeDuplicateKey_guestName);
        System.out.println("makeDuplicateKey.result=" + _makeDuplicateKey__return);


        }
        {
        System.out.println("Invoking publishFaultList...");
        uk.co.noetic.kaba.PublishFaultListResponse.PublishFaultListResult _publishFaultList__return = port.publishFaultList();
        System.out.println("publishFaultList.result=" + _publishFaultList__return);


        }
        {
        System.out.println("Invoking updateKeyTransactionStatus...");
        uk.co.noetic.kaba.UpdateKeyTransactionStatus _updateKeyTransactionStatus_parameters = null;
        uk.co.noetic.kaba.UpdateKeyTransactionStatusResponse _updateKeyTransactionStatus__return = port.updateKeyTransactionStatus(_updateKeyTransactionStatus_parameters);
        System.out.println("updateKeyTransactionStatus.result=" + _updateKeyTransactionStatus__return);


        }
        {
        System.out.println("Invoking cancelGuestsAccessToRoom...");
        java.lang.String _cancelGuestsAccessToRoom_siteName = "";
        java.lang.String _cancelGuestsAccessToRoom_mainRoomNo = "";
        java.lang.String _cancelGuestsAccessToRoom_pmsTerminalID = "";
        uk.co.noetic.kaba.CancelGuestsAccessToRoomResponse.CancelGuestsAccessToRoomResult _cancelGuestsAccessToRoom__return = port.cancelGuestsAccessToRoom(_cancelGuestsAccessToRoom_siteName, _cancelGuestsAccessToRoom_mainRoomNo, _cancelGuestsAccessToRoom_pmsTerminalID);
        System.out.println("cancelGuestsAccessToRoom.result=" + _cancelGuestsAccessToRoom__return);


        }
        {
        System.out.println("Invoking extendCheckOut...");
        java.lang.String _extendCheckOut_reservationID = "";
        java.lang.String _extendCheckOut_siteName = "";
        java.lang.String _extendCheckOut_pmsTerminalID = "";
        javax.xml.datatype.XMLGregorianCalendar _extendCheckOut_checkOut = null;
        uk.co.noetic.kaba.ExtendCheckOutResponse.ExtendCheckOutResult _extendCheckOut__return = port.extendCheckOut(_extendCheckOut_reservationID, _extendCheckOut_siteName, _extendCheckOut_pmsTerminalID, _extendCheckOut_checkOut);
        System.out.println("extendCheckOut.result=" + _extendCheckOut__return);


        }
        {
        System.out.println("Invoking getDeviceSecKeysRights...");
        uk.co.noetic.kaba.CSecKeysRequest _getDeviceSecKeysRights_keyReqVal = null;
        javax.xml.ws.Holder<uk.co.noetic.kaba.CSecKeysRequest> _getDeviceSecKeysRights_keyReq = new javax.xml.ws.Holder<uk.co.noetic.kaba.CSecKeysRequest>(_getDeviceSecKeysRights_keyReqVal);
        javax.xml.ws.Holder<uk.co.noetic.kaba.GetDeviceSecKeysRightsResponse.GetDeviceSecKeysRightsResult> _getDeviceSecKeysRights_getDeviceSecKeysRightsResult = new javax.xml.ws.Holder<uk.co.noetic.kaba.GetDeviceSecKeysRightsResponse.GetDeviceSecKeysRightsResult>();
        port.getDeviceSecKeysRights(_getDeviceSecKeysRights_keyReq, _getDeviceSecKeysRights_getDeviceSecKeysRightsResult);

        System.out.println("getDeviceSecKeysRights._getDeviceSecKeysRights_keyReq=" + _getDeviceSecKeysRights_keyReq.value);
        System.out.println("getDeviceSecKeysRights._getDeviceSecKeysRights_getDeviceSecKeysRightsResult=" + _getDeviceSecKeysRights_getDeviceSecKeysRightsResult.value);

        }
        {
        System.out.println("Invoking unRegisterStaff...");
        java.lang.String _unRegisterStaff_staffID = "";
        java.lang.String _unRegisterStaff_mobileNumber = "";
        java.lang.String _unRegisterStaff_keyName = "";
        byte[] _unRegisterStaff_keyData = new byte[0];
        uk.co.noetic.kaba.CMessengerGuestCreateResponse _unRegisterStaff__return = port.unRegisterStaff(_unRegisterStaff_staffID, _unRegisterStaff_mobileNumber, _unRegisterStaff_keyName, _unRegisterStaff_keyData);
        System.out.println("unRegisterStaff.result=" + _unRegisterStaff__return);


        }
        {
        System.out.println("Invoking createOneShotKey...");
        java.lang.String _createOneShotKey_siteName = "";
        java.lang.String _createOneShotKey_pmsTerminalID = "";
        java.lang.String _createOneShotKey_encoderID = "";
        java.lang.String _createOneShotKey_mainRoomNo = "";
        javax.xml.datatype.XMLGregorianCalendar _createOneShotKey_checkIn = null;
        javax.xml.datatype.XMLGregorianCalendar _createOneShotKey_checkOut = null;
        long _createOneShotKey_keySize = 0;
        java.lang.String _createOneShotKey_uid = "";
        uk.co.noetic.kaba.CreateOneShotKeyResponse.CreateOneShotKeyResult _createOneShotKey__return = port.createOneShotKey(_createOneShotKey_siteName, _createOneShotKey_pmsTerminalID, _createOneShotKey_encoderID, _createOneShotKey_mainRoomNo, _createOneShotKey_checkIn, _createOneShotKey_checkOut, _createOneShotKey_keySize, _createOneShotKey_uid);
        System.out.println("createOneShotKey.result=" + _createOneShotKey__return);


        }
        {
        System.out.println("Invoking reEstablishAccessToGuest...");
        java.lang.String _reEstablishAccessToGuest_reservationID = "";
        java.lang.String _reEstablishAccessToGuest_siteName = "";
        java.lang.String _reEstablishAccessToGuest_pmsTerminalID = "";
        uk.co.noetic.kaba.ReEstablishAccessToGuestResponse.ReEstablishAccessToGuestResult _reEstablishAccessToGuest__return = port.reEstablishAccessToGuest(_reEstablishAccessToGuest_reservationID, _reEstablishAccessToGuest_siteName, _reEstablishAccessToGuest_pmsTerminalID);
        System.out.println("reEstablishAccessToGuest.result=" + _reEstablishAccessToGuest__return);


        }
        {
        System.out.println("Invoking publishResponseComplexTypes...");
        uk.co.noetic.kaba.CMessengerResponse _publishResponseComplexTypes_dummyResponse = null;
        uk.co.noetic.kaba.Fault _publishResponseComplexTypes_dummyFault = null;
        uk.co.noetic.kaba.EMainFaultReasons _publishResponseComplexTypes_aReason = null;
        uk.co.noetic.kaba.EDetailEncoderFaultReasons _publishResponseComplexTypes_aDetailReason = null;
        uk.co.noetic.kaba.PublishResponseComplexTypesResponse.PublishResponseComplexTypesResult _publishResponseComplexTypes__return = port.publishResponseComplexTypes(_publishResponseComplexTypes_dummyResponse, _publishResponseComplexTypes_dummyFault, _publishResponseComplexTypes_aReason, _publishResponseComplexTypes_aDetailReason);
        System.out.println("publishResponseComplexTypes.result=" + _publishResponseComplexTypes__return);


        }
        {
        System.out.println("Invoking makeUnassignedBooking...");
        uk.co.noetic.kaba.MakeUnassignedBooking _makeUnassignedBooking_parameters = null;
        uk.co.noetic.kaba.MakeUnassignedBookingResponse _makeUnassignedBooking__return = port.makeUnassignedBooking(_makeUnassignedBooking_parameters);
        System.out.println("makeUnassignedBooking.result=" + _makeUnassignedBooking__return);


        }
        {
        System.out.println("Invoking checkOutGuest...");
        java.lang.String _checkOutGuest_reservationID = "";
        java.lang.String _checkOutGuest_siteName = "";
        java.lang.String _checkOutGuest_pmsTerminalID = "";
        uk.co.noetic.kaba.CheckOutGuestResponse.CheckOutGuestResult _checkOutGuest__return = port.checkOutGuest(_checkOutGuest_reservationID, _checkOutGuest_siteName, _checkOutGuest_pmsTerminalID);
        System.out.println("checkOutGuest.result=" + _checkOutGuest__return);


        }
        {
        System.out.println("Invoking changeKeyAccess...");
        uk.co.noetic.kaba.ChangeKeyAccess _changeKeyAccess_parameters = null;
        uk.co.noetic.kaba.ChangeKeyAccessResponse _changeKeyAccess__return = port.changeKeyAccess(_changeKeyAccess_parameters);
        System.out.println("changeKeyAccess.result=" + _changeKeyAccess__return);


        }
        {
        System.out.println("Invoking cancelGuestsMobileAccessToRoom...");
        java.lang.String _cancelGuestsMobileAccessToRoom_siteName = "";
        java.lang.String _cancelGuestsMobileAccessToRoom_reservationID = "";
        java.lang.String _cancelGuestsMobileAccessToRoom_mainRoomNo = "";
        java.lang.String _cancelGuestsMobileAccessToRoom_guestMobileNumber = "";
        java.lang.String _cancelGuestsMobileAccessToRoom_pmsTerminalID = "";
        uk.co.noetic.kaba.CancelGuestsMobileAccessToRoomResponse.CancelGuestsMobileAccessToRoomResult _cancelGuestsMobileAccessToRoom__return = port.cancelGuestsMobileAccessToRoom(_cancelGuestsMobileAccessToRoom_siteName, _cancelGuestsMobileAccessToRoom_reservationID, _cancelGuestsMobileAccessToRoom_mainRoomNo, _cancelGuestsMobileAccessToRoom_guestMobileNumber, _cancelGuestsMobileAccessToRoom_pmsTerminalID);
        System.out.println("cancelGuestsMobileAccessToRoom.result=" + _cancelGuestsMobileAccessToRoom__return);


        }
        {
        System.out.println("Invoking sendKey2StaffMobileDevice...");
        java.lang.String _sendKey2StaffMobileDevice_pmsTerminalID = "";
        javax.xml.datatype.XMLGregorianCalendar _sendKey2StaffMobileDevice_validFrom = null;
        javax.xml.datatype.XMLGregorianCalendar _sendKey2StaffMobileDevice_validTo = null;
        java.lang.String _sendKey2StaffMobileDevice_staffID = "";
        java.lang.String _sendKey2StaffMobileDevice_name = "";
        java.lang.String _sendKey2StaffMobileDevice_mobileNumber = "";
        java.lang.String _sendKey2StaffMobileDevice_keyName = "";
        byte[] _sendKey2StaffMobileDevice_keyData = new byte[0];
        boolean _sendKey2StaffMobileDevice_sendSMS = false;
        uk.co.noetic.kaba.CMessengerGuestCreateResponse _sendKey2StaffMobileDevice__return = port.sendKey2StaffMobileDevice(_sendKey2StaffMobileDevice_pmsTerminalID, _sendKey2StaffMobileDevice_validFrom, _sendKey2StaffMobileDevice_validTo, _sendKey2StaffMobileDevice_staffID, _sendKey2StaffMobileDevice_name, _sendKey2StaffMobileDevice_mobileNumber, _sendKey2StaffMobileDevice_keyName, _sendKey2StaffMobileDevice_keyData, _sendKey2StaffMobileDevice_sendSMS);
        System.out.println("sendKey2StaffMobileDevice.result=" + _sendKey2StaffMobileDevice__return);


        }
        {
        System.out.println("Invoking getMobileTransactionHistory...");
        java.lang.String _getMobileTransactionHistory_reservationID = "";
        java.lang.String _getMobileTransactionHistory_roomNo = "";
        java.lang.String _getMobileTransactionHistory_encoderID = "";
        javax.xml.datatype.XMLGregorianCalendar _getMobileTransactionHistory_from = null;
        javax.xml.datatype.XMLGregorianCalendar _getMobileTransactionHistory_to = null;
        uk.co.noetic.kaba.MobileTransactionHistory _getMobileTransactionHistory__return = port.getMobileTransactionHistory(_getMobileTransactionHistory_reservationID, _getMobileTransactionHistory_roomNo, _getMobileTransactionHistory_encoderID, _getMobileTransactionHistory_from, _getMobileTransactionHistory_to);
        System.out.println("getMobileTransactionHistory.result=" + _getMobileTransactionHistory__return);


        }
        {
        System.out.println("Invoking addGuestAccess...");
        java.lang.String _addGuestAccess_reservationID = "";
        java.lang.String _addGuestAccess_siteName = "";
        java.lang.String _addGuestAccess_pmsTerminalID = "";
        uk.co.noetic.kaba.ArrayOfString _addGuestAccess_roomList = null;
        uk.co.noetic.kaba.AddGuestAccessResponse.AddGuestAccessResult _addGuestAccess__return = port.addGuestAccess(_addGuestAccess_reservationID, _addGuestAccess_siteName, _addGuestAccess_pmsTerminalID, _addGuestAccess_roomList);
        System.out.println("addGuestAccess.result=" + _addGuestAccess__return);


        }

        System.exit(0);
    }

}
