
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package uk.co.noetic.kaba;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-10-26T10:26:57.339+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "MessengerPMSWSService",
                      portName = "MessengerPMSWSServiceSoap",
                      targetNamespace = "http://tempuri.org",
                      wsdlLocation = "file:/C:/Users/sampa/AppData/Local/Temp/tempdir7801692537910433554.tmp/MessengerPMSService_1.wsdl",
                      endpointInterface = "uk.co.noetic.kaba.MessengerPMSWSServiceSoap")
                      
public class MessengerPMSWSServiceSoapImpl1 implements MessengerPMSWSServiceSoap {

    private static final Logger LOG = Logger.getLogger(MessengerPMSWSServiceSoapImpl1.class.getName());

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#changeGuestAccess(java.lang.String  reservationID ,)java.lang.String  siteName ,)java.lang.String  pmsTerminalID ,)java.lang.String  mainRoomNo ,)uk.co.noetic.kaba.ArrayOfString  roomList )*
     */
    public uk.co.noetic.kaba.ChangeGuestAccessResponse.ChangeGuestAccessResult changeGuestAccess(java.lang.String reservationID,java.lang.String siteName,java.lang.String pmsTerminalID,java.lang.String mainRoomNo,uk.co.noetic.kaba.ArrayOfString roomList) { 
        LOG.info("Executing operation changeGuestAccess");
        System.out.println(reservationID);
        System.out.println(siteName);
        System.out.println(pmsTerminalID);
        System.out.println(mainRoomNo);
        System.out.println(roomList);
        try {
            uk.co.noetic.kaba.ChangeGuestAccessResponse.ChangeGuestAccessResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#denyAccessToGuest(java.lang.String  reservationID ,)java.lang.String  siteName ,)java.lang.String  pmsTerminalID )*
     */
    public uk.co.noetic.kaba.DenyAccessToGuestResponse.DenyAccessToGuestResult denyAccessToGuest(java.lang.String reservationID,java.lang.String siteName,java.lang.String pmsTerminalID) { 
        LOG.info("Executing operation denyAccessToGuest");
        System.out.println(reservationID);
        System.out.println(siteName);
        System.out.println(pmsTerminalID);
        try {
            uk.co.noetic.kaba.DenyAccessToGuestResponse.DenyAccessToGuestResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#createNewBooking(uk.co.noetic.kaba.CreateNewBooking  parameters )*
     */
    public uk.co.noetic.kaba.CreateNewBookingResponse createNewBooking(CreateNewBooking parameters) { 
        LOG.info("Executing operation createNewBooking");
        System.out.println(parameters);
        try {
            uk.co.noetic.kaba.CreateNewBookingResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#helloWorldTest(java.lang.String  s1 ,)int  i1 )*
     */
    public java.lang.String helloWorldTest(java.lang.String s1,int i1) { 
        LOG.info("Executing operation helloWorldTest");
        System.out.println(s1);
        System.out.println(i1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#addSharedGuest(uk.co.noetic.kaba.AddSharedGuest  parameters )*
     */
    public uk.co.noetic.kaba.AddSharedGuestResponse addSharedGuest(AddSharedGuest parameters) { 
        LOG.info("Executing operation addSharedGuest");
        System.out.println(parameters);
        try {
            uk.co.noetic.kaba.AddSharedGuestResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#makeDuplicateKey(java.lang.String  reservationID ,)java.lang.String  siteName ,)java.lang.String  pmsTerminalID ,)java.lang.String  encoderID ,)long  keyCount ,)long  keySize ,)java.lang.String  uid ,)java.lang.String  guestName )*
     */
    public uk.co.noetic.kaba.MakeDuplicateKeyResponse.MakeDuplicateKeyResult makeDuplicateKey(java.lang.String reservationID,java.lang.String siteName,java.lang.String pmsTerminalID,java.lang.String encoderID,long keyCount,long keySize,java.lang.String uid,java.lang.String guestName) { 
        LOG.info("Executing operation makeDuplicateKey");
        System.out.println(reservationID);
        System.out.println(siteName);
        System.out.println(pmsTerminalID);
        System.out.println(encoderID);
        System.out.println(keyCount);
        System.out.println(keySize);
        System.out.println(uid);
        System.out.println(guestName);
        try {
            uk.co.noetic.kaba.MakeDuplicateKeyResponse.MakeDuplicateKeyResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#publishFaultList(*
     */
    public uk.co.noetic.kaba.PublishFaultListResponse.PublishFaultListResult publishFaultList() { 
        LOG.info("Executing operation publishFaultList");
        try {
            uk.co.noetic.kaba.PublishFaultListResponse.PublishFaultListResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#updateKeyTransactionStatus(uk.co.noetic.kaba.UpdateKeyTransactionStatus  parameters )*
     */
    public uk.co.noetic.kaba.UpdateKeyTransactionStatusResponse updateKeyTransactionStatus(UpdateKeyTransactionStatus parameters) { 
        LOG.info("Executing operation updateKeyTransactionStatus");
        System.out.println(parameters);
        try {
            uk.co.noetic.kaba.UpdateKeyTransactionStatusResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#cancelGuestsAccessToRoom(java.lang.String  siteName ,)java.lang.String  mainRoomNo ,)java.lang.String  pmsTerminalID )*
     */
    public uk.co.noetic.kaba.CancelGuestsAccessToRoomResponse.CancelGuestsAccessToRoomResult cancelGuestsAccessToRoom(java.lang.String siteName,java.lang.String mainRoomNo,java.lang.String pmsTerminalID) { 
        LOG.info("Executing operation cancelGuestsAccessToRoom");
        System.out.println(siteName);
        System.out.println(mainRoomNo);
        System.out.println(pmsTerminalID);
        try {
            uk.co.noetic.kaba.CancelGuestsAccessToRoomResponse.CancelGuestsAccessToRoomResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#extendCheckOut(java.lang.String  reservationID ,)java.lang.String  siteName ,)java.lang.String  pmsTerminalID ,)javax.xml.datatype.XMLGregorianCalendar  checkOut )*
     */
    public uk.co.noetic.kaba.ExtendCheckOutResponse.ExtendCheckOutResult extendCheckOut(java.lang.String reservationID,java.lang.String siteName,java.lang.String pmsTerminalID,javax.xml.datatype.XMLGregorianCalendar checkOut) { 
        LOG.info("Executing operation extendCheckOut");
        System.out.println(reservationID);
        System.out.println(siteName);
        System.out.println(pmsTerminalID);
        System.out.println(checkOut);
        try {
            uk.co.noetic.kaba.ExtendCheckOutResponse.ExtendCheckOutResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#getDeviceSecKeysRights(uk.co.noetic.kaba.CSecKeysRequest  keyReq ,)uk.co.noetic.kaba.GetDeviceSecKeysRightsResponse.GetDeviceSecKeysRightsResult  getDeviceSecKeysRightsResult )*
     */
    public void getDeviceSecKeysRights(javax.xml.ws.Holder<CSecKeysRequest> keyReq,javax.xml.ws.Holder<uk.co.noetic.kaba.GetDeviceSecKeysRightsResponse.GetDeviceSecKeysRightsResult> getDeviceSecKeysRightsResult) { 
        LOG.info("Executing operation getDeviceSecKeysRights");
        System.out.println(keyReq.value);
        try {
            uk.co.noetic.kaba.GetDeviceSecKeysRightsResponse.GetDeviceSecKeysRightsResult getDeviceSecKeysRightsResultValue = null;
            getDeviceSecKeysRightsResult.value = getDeviceSecKeysRightsResultValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#unRegisterStaff(java.lang.String  staffID ,)java.lang.String  mobileNumber ,)java.lang.String  keyName ,)byte[]  keyData )*
     */
    public uk.co.noetic.kaba.CMessengerGuestCreateResponse unRegisterStaff(java.lang.String staffID,java.lang.String mobileNumber,java.lang.String keyName,byte[] keyData) { 
        LOG.info("Executing operation unRegisterStaff");
        System.out.println(staffID);
        System.out.println(mobileNumber);
        System.out.println(keyName);
        System.out.println(keyData);
        try {
            uk.co.noetic.kaba.CMessengerGuestCreateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#createOneShotKey(java.lang.String  siteName ,)java.lang.String  pmsTerminalID ,)java.lang.String  encoderID ,)java.lang.String  mainRoomNo ,)javax.xml.datatype.XMLGregorianCalendar  checkIn ,)javax.xml.datatype.XMLGregorianCalendar  checkOut ,)long  keySize ,)java.lang.String  uid )*
     */
    public uk.co.noetic.kaba.CreateOneShotKeyResponse.CreateOneShotKeyResult createOneShotKey(java.lang.String siteName,java.lang.String pmsTerminalID,java.lang.String encoderID,java.lang.String mainRoomNo,javax.xml.datatype.XMLGregorianCalendar checkIn,javax.xml.datatype.XMLGregorianCalendar checkOut,long keySize,java.lang.String uid) { 
        LOG.info("Executing operation createOneShotKey");
        System.out.println(siteName);
        System.out.println(pmsTerminalID);
        System.out.println(encoderID);
        System.out.println(mainRoomNo);
        System.out.println(checkIn);
        System.out.println(checkOut);
        System.out.println(keySize);
        System.out.println(uid);
        try {
            uk.co.noetic.kaba.CreateOneShotKeyResponse.CreateOneShotKeyResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#reEstablishAccessToGuest(java.lang.String  reservationID ,)java.lang.String  siteName ,)java.lang.String  pmsTerminalID )*
     */
    public uk.co.noetic.kaba.ReEstablishAccessToGuestResponse.ReEstablishAccessToGuestResult reEstablishAccessToGuest(java.lang.String reservationID,java.lang.String siteName,java.lang.String pmsTerminalID) { 
        LOG.info("Executing operation reEstablishAccessToGuest");
        System.out.println(reservationID);
        System.out.println(siteName);
        System.out.println(pmsTerminalID);
        try {
            uk.co.noetic.kaba.ReEstablishAccessToGuestResponse.ReEstablishAccessToGuestResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#publishResponseComplexTypes(uk.co.noetic.kaba.CMessengerResponse  dummyResponse ,)uk.co.noetic.kaba.Fault  dummyFault ,)uk.co.noetic.kaba.EMainFaultReasons  aReason ,)uk.co.noetic.kaba.EDetailEncoderFaultReasons  aDetailReason )*
     */
    public uk.co.noetic.kaba.PublishResponseComplexTypesResponse.PublishResponseComplexTypesResult publishResponseComplexTypes(uk.co.noetic.kaba.CMessengerResponse dummyResponse,uk.co.noetic.kaba.Fault dummyFault,uk.co.noetic.kaba.EMainFaultReasons aReason,uk.co.noetic.kaba.EDetailEncoderFaultReasons aDetailReason) { 
        LOG.info("Executing operation publishResponseComplexTypes");
        System.out.println(dummyResponse);
        System.out.println(dummyFault);
        System.out.println(aReason);
        System.out.println(aDetailReason);
        try {
            uk.co.noetic.kaba.PublishResponseComplexTypesResponse.PublishResponseComplexTypesResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#makeUnassignedBooking(uk.co.noetic.kaba.MakeUnassignedBooking  parameters )*
     */
    public uk.co.noetic.kaba.MakeUnassignedBookingResponse makeUnassignedBooking(MakeUnassignedBooking parameters) { 
        LOG.info("Executing operation makeUnassignedBooking");
        System.out.println(parameters);
        try {
            uk.co.noetic.kaba.MakeUnassignedBookingResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#checkOutGuest(java.lang.String  reservationID ,)java.lang.String  siteName ,)java.lang.String  pmsTerminalID )*
     */
    public uk.co.noetic.kaba.CheckOutGuestResponse.CheckOutGuestResult checkOutGuest(java.lang.String reservationID,java.lang.String siteName,java.lang.String pmsTerminalID) { 
        LOG.info("Executing operation checkOutGuest");
        System.out.println(reservationID);
        System.out.println(siteName);
        System.out.println(pmsTerminalID);
        try {
            uk.co.noetic.kaba.CheckOutGuestResponse.CheckOutGuestResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#changeKeyAccess(uk.co.noetic.kaba.ChangeKeyAccess  parameters )*
     */
    public uk.co.noetic.kaba.ChangeKeyAccessResponse changeKeyAccess(ChangeKeyAccess parameters) { 
        LOG.info("Executing operation changeKeyAccess");
        System.out.println(parameters);
        try {
            uk.co.noetic.kaba.ChangeKeyAccessResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#cancelGuestsMobileAccessToRoom(java.lang.String  siteName ,)java.lang.String  reservationID ,)java.lang.String  mainRoomNo ,)java.lang.String  guestMobileNumber ,)java.lang.String  pmsTerminalID )*
     */
    public uk.co.noetic.kaba.CancelGuestsMobileAccessToRoomResponse.CancelGuestsMobileAccessToRoomResult cancelGuestsMobileAccessToRoom(java.lang.String siteName,java.lang.String reservationID,java.lang.String mainRoomNo,java.lang.String guestMobileNumber,java.lang.String pmsTerminalID) { 
        LOG.info("Executing operation cancelGuestsMobileAccessToRoom");
        System.out.println(siteName);
        System.out.println(reservationID);
        System.out.println(mainRoomNo);
        System.out.println(guestMobileNumber);
        System.out.println(pmsTerminalID);
        try {
            uk.co.noetic.kaba.CancelGuestsMobileAccessToRoomResponse.CancelGuestsMobileAccessToRoomResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#sendKey2StaffMobileDevice(java.lang.String  pmsTerminalID ,)javax.xml.datatype.XMLGregorianCalendar  validFrom ,)javax.xml.datatype.XMLGregorianCalendar  validTo ,)java.lang.String  staffID ,)java.lang.String  name ,)java.lang.String  mobileNumber ,)java.lang.String  keyName ,)byte[]  keyData ,)boolean  sendSMS )*
     */
    public uk.co.noetic.kaba.CMessengerGuestCreateResponse sendKey2StaffMobileDevice(java.lang.String pmsTerminalID,javax.xml.datatype.XMLGregorianCalendar validFrom,javax.xml.datatype.XMLGregorianCalendar validTo,java.lang.String staffID,java.lang.String name,java.lang.String mobileNumber,java.lang.String keyName,byte[] keyData,boolean sendSMS) { 
        LOG.info("Executing operation sendKey2StaffMobileDevice");
        System.out.println(pmsTerminalID);
        System.out.println(validFrom);
        System.out.println(validTo);
        System.out.println(staffID);
        System.out.println(name);
        System.out.println(mobileNumber);
        System.out.println(keyName);
        System.out.println(keyData);
        System.out.println(sendSMS);
        try {
            uk.co.noetic.kaba.CMessengerGuestCreateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#getMobileTransactionHistory(java.lang.String  reservationID ,)java.lang.String  roomNo ,)java.lang.String  encoderID ,)javax.xml.datatype.XMLGregorianCalendar  from ,)javax.xml.datatype.XMLGregorianCalendar  to )*
     */
    public uk.co.noetic.kaba.MobileTransactionHistory getMobileTransactionHistory(java.lang.String reservationID,java.lang.String roomNo,java.lang.String encoderID,javax.xml.datatype.XMLGregorianCalendar from,javax.xml.datatype.XMLGregorianCalendar to) { 
        LOG.info("Executing operation getMobileTransactionHistory");
        System.out.println(reservationID);
        System.out.println(roomNo);
        System.out.println(encoderID);
        System.out.println(from);
        System.out.println(to);
        try {
            uk.co.noetic.kaba.MobileTransactionHistory _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uk.co.noetic.kaba.MessengerPMSWSServiceSoap#addGuestAccess(java.lang.String  reservationID ,)java.lang.String  siteName ,)java.lang.String  pmsTerminalID ,)uk.co.noetic.kaba.ArrayOfString  roomList )*
     */
    public uk.co.noetic.kaba.AddGuestAccessResponse.AddGuestAccessResult addGuestAccess(java.lang.String reservationID,java.lang.String siteName,java.lang.String pmsTerminalID,uk.co.noetic.kaba.ArrayOfString roomList) { 
        LOG.info("Executing operation addGuestAccess");
        System.out.println(reservationID);
        System.out.println(siteName);
        System.out.println(pmsTerminalID);
        System.out.println(roomList);
        try {
            uk.co.noetic.kaba.AddGuestAccessResponse.AddGuestAccessResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
